# Generated by Django 5.2.7 on 2025-11-29 22:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_alter_bankconnection_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingsgoal',
            old_name='current_savings',
            new_name='current_amount',
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='goal_type',
            field=models.CharField(choices=[('savings', 'Savings Goal'), ('payoff', 'Debt Payoff Goal'), ('expense', 'Expense Goal')], default='savings', max_length=32),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='GoalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='mainpage.savingsgoal')),
            ],
        ),
    ]
